IECS_SESR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('SE_server.urls')),
]

SE_server/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', ProjectView.as_view(), name='project'),
    path('project/<str:pk>/', ProjectInformation.as_view(), name='Project_Information'),
    path('project/<str:pk>/create', ProjectCreateView.as_view(), name='add_project'),
    path('project/<str:pk>/edit', ProjectEditView.as_view(), name='edit_project'),
    path('project/<str:pk>/delete', ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<str:pk>/testmemberlist/', TestMemberView.as_view(), name='TML'),
    path('project/<str:pk>/testmemberlist/upload', TestMemberUploadView.as_view(), name='upload_TML'),
    path('project/<str:pk>/testmemberlist/upload/UID', TestMemberUploadUIDView.as_view(), name='upload_TML_UID'),
    path('project/<str:pk>/testmemberlist/create', TestMemberCreateView.as_view(), name='create_TML'),
    path('project/<str:pk>/testmemberlist/edit/<int:id>', TestMemberEditView.as_view(), name='edit_TML'),
    path('project/<str:pk>/testmemberlist/delete/<int:id>', TestMemberDeleteView.as_view(), name='delete_TML'),
    path('project/<str:pk>/projectmail/', ProjectMail.as_view(), name='PM'),
    path('project/<str:pk>/projectmail/upload', ProjectMailUploadView.as_view(), name='upload_PM'),
    path('project/<str:pk>/projectmail/create', ProjectMailCreateView.as_view(), name='create_PM'),
    path('project/<str:pk>/projectmail/edit/<int:id>', ProjectMailEditView.as_view(), name='edit_PM'),
    path('project/<str:pk>/projectmail/delete/<int:id>', ProjectMailDeleteView.as_view(), name='delete_PM'),
    path('project/<str:pk>/result/', ProjectResultView.as_view(), name='PR'),
    # path('project/<str:pk>/result/graph', ProjectResultGraphView.as_view(), name='PR_Graph'),
    path('project/<str:pk>/result/open_record', ProjectOpenRecordView.as_view(), name='PR_open_record'),
    path('project/<str:pk>/result/click_record', ProjectClickRecordView.as_view(), name='PR_click_record'),
    path('project/<str:pk>/result/attach_record', ProjectAttachmentRecordView.as_view(), name='PR_attachment_record'),
    path('project/<str:pk>/Mail_System/', MailSystem.as_view(), name='Mail_System'),
    path('project/<str:pk>/Mail_Recipient/', MailRecipients.as_view(), name='Mail_Recipient'),
    path('project/<str:pk>/Mail_Check/', MailCheck.as_view(), name='Mail_Check'),
    path('project/<str:pk>/Mail_Send/', MailSend.as_view(), name='Mail_Send'),
    path('project/<str:pk>/mail_record/', SendRecord.as_view(), name='mail_record'),
    path('project/<str:pk>/mail_upload/<int:id>', MailUpload.as_view(), name='upload_mail'),
    path('project/<str:pk>/attachment_upload/<int:id>', AttachUpload.as_view(), name='attachment_upload'),
    path('project/<str:pk>/mail_view/<int:id>', MailView.as_view(), name='mail_file'),
    path('project/<str:pk>/mail_download/<int:id>', DownloadMail.as_view(), name='mail_download'),
    # path('project/<str:pk>/mail_delete/<int:id>', MailDelete.as_view(), name='mail_delete'),
    path('company/', CompamyView.as_view(), name='company'),
    path('company/create', CompanyCreateView.as_view(), name='company_create'),
    path('company/<str:pk>/delete', CompanyDeleteView.as_view(), name='company_delete'),
    path('company/<str:pk>/user', CompanyUserView.as_view(), name='user'),
    path('company/<str:pk>/user/create', UserCreateView.as_view(), name='user_create'),
    path('company/<str:pk>/user/<int:id>/delete', UserDeleteView.as_view(), name='user_delete'),
    path('company/<str:pk>/user/<int:id>/edit/<str:url>', UserEditView.as_view(), name='user_edit'),
    path('user/activate/<token>/', EmailValidators.active_user, name='user_active'),
    path('user/forgotpsw/<token>/', EmailValidators.user_forgotpsw, name='user_forgotpsw'),
    path('user/passwordreset', PasswordResetView.as_view(), name='user_password_reset'),
    path('login/', LoginView.as_view(), name='login'),
    path('forgotpassword/', ForgotPasswordView.as_view(), name='forgot_password'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('download/<str:type>', DownloadExample.as_view(), name='download'),
    path('report_back', report_back, name='report_back'),
    path('report_back_success', report_back_success, name='report_back_success'),
    path('report_back_fail', report_back_fail, name='report_back_fail'),
    path('project/<str:pk>/result/all_score', ProjectAllScoreView.as_view(), name='PR_all_score'),
    path('all_score', all_score, name='all_score')
]

SE_server/models.py
from django.db import models
from django.contrib.auth.models import *
from django.core.files.storage import *


class Company(models.Model):
    GroupCode = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='Company')
    CompanyCode = models.CharField(max_length=255, primary_key=True)
    CompanyName = models.CharField(max_length=255)
    ProjectCount = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.CompanyCode

    class Meta:
        permissions = (
            ('exe_company', 'Execute Company'),
        )


def html_upload_to(instance, filename):
    return 'MailFile/{project_code}/{filename}'.format(project_code=instance.ProjectCode, filename=filename)


class MailList(models.Model):
    ProjectCode = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='Mail')
    id = models.BigAutoField(primary_key=True)
    MailNumber = models.CharField(max_length=255)
    Type = models.CharField(max_length=100, null=True, blank=True)
    Title = models.CharField(max_length=255, null=True, blank=True)
    Sender = models.CharField(max_length=255, null=True, blank=True)
    Sender_Mail = models.CharField(max_length=255, null=True, blank=True)
    HasAtt = models.BooleanField(default=False, null=True, blank=True)
    Address = models.CharField(max_length=255)
    Open = models.CharField(max_length=255)
    Click = models.CharField(max_length=255)
    Attachment = models.CharField(max_length=255, null=True, blank=True)
    MailTag = models.CharField(max_length=255, null=True, blank=True, default=None)
    filepath = models.FileField(upload_to=html_upload_to, default=None, null=True, blank=True)
    AttachmentFile = models.FileField(upload_to=html_upload_to, default=None, null=True, blank=True)

    def __str__(self):
        return str(self.id)

    class Meta:
        unique_together = ('ProjectCode', 'MailNumber')


class Project(models.Model):
    CompanyCode = models.ForeignKey('Company', on_delete=models.CASCADE, related_name='Company', blank=True)
    ProjectCode = models.CharField(max_length=50, primary_key=True)
    ProjectName = models.CharField(max_length=255, blank=True)
    CalculateStartDate = models.DateTimeField(null=True, blank=True)
    CalculateEndDate = models.DateTimeField(null=True, blank=True)
    PersonCount = models.IntegerField(null=True, blank=True)
    UnitList = models.JSONField(null=True, blank=True)
    MailCount = models.IntegerField(null=True, blank=True)
    ProjectResult = models.JSONField(null=True, blank=True)
    OpenRecord = models.JSONField(null=True, blank=True, default=None)
    ClickRecord = models.JSONField(null=True, blank=True, default=None)
    AttachmentRecord = models.JSONField(null=True, blank=True, default=None)
    SendRecord = models.JSONField(null=True, blank=True, default=None)
    lastCalTime = models.DateTimeField(null=True, blank=True, default=None)
    IgnoreSecond = models.IntegerField(null=True, default=60)

    def __str__(self):
        return self.ProjectCode

    class Meta:
        permissions = (
            ('exe_project', 'Execute Project'),
        )


class TestMemberList(models.Model):
    ProjectCode = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='TestML')
    id = models.BigAutoField(primary_key=True)
    Unit = models.CharField(max_length=10, null=True, blank=True, )
    UnitName = models.CharField(max_length=255, null=True, blank=True, default=None)
    MemberNumber = models.CharField(max_length=10)
    UUID = models.CharField(max_length=20, null=True, blank=True)
    Email = models.EmailField()
    Result = models.JSONField(null=True, blank=True)

    def __str__(self):
        return self.MemberNumber

    class Meta:
        unique_together = [('ProjectCode', 'MemberNumber'), ('ProjectCode', 'Email')]


class TestMemberListTemp(models.Model):
    ProjectCode = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='TestML_Temp')
    id = models.BigAutoField(primary_key=True)
    UnitName = models.CharField(max_length=255, null=True, blank=True, default=None)
    MemberNumber = models.CharField(max_length=10)
    UUID = models.CharField(max_length=20, null=True, blank=True)
    Email = models.EmailField()

    def __str__(self):
        return self.MemberNumber


class Log(models.Model):
    date = models.CharField(max_length=20, db_collation='utf8_general_ci')
    time = models.CharField(max_length=20, db_collation='utf8_general_ci')
    html = models.CharField(max_length=255, db_collation='utf8_general_ci')
    uuid = models.CharField(max_length=20, db_collation='utf8_general_ci')
    id = models.BigAutoField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'log'


class File(models.Model):
    ProjectCode = models.ForeignKey('Project', on_delete=models.CASCADE, related_name='Mail_File', default=None)
    id = models.BigAutoField(primary_key=True)
    filename = models.CharField(max_length=255)
    sender = models.CharField(max_length=255, default=None)
    filepath = models.FileField(upload_to=html_upload_to)


class Score(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE, related_name='std_score', default=None)
    group_code = models.CharField(max_length=255)
    group_name = models.CharField(max_length=255)
    mail1 = models.IntegerField(null=True, blank=True)
    mail2 = models.IntegerField(null=True, blank=True)
    mail3 = models.IntegerField(null=True, blank=True)


class ReportBackRecord(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE, related_name='std_rb', default=None)
    group_code = models.CharField(max_length=255)
    group_name = models.CharField(max_length=255)
    content = models.CharField(max_length=255, null=True, blank=True)
    check_result = models.BooleanField(null=True, blank=True)
    report_ime = models.DateTimeField(default=timezone.now)
# Create your models here.

SE_server/forms.py
from dataclasses import field
from pyexpat import model
from tkinter import Widget
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from .models import *


class LoginForm(forms.Form):
    email = forms.EmailField(
        label="電子郵件",
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label="密碼",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )


class RegisterForm(UserCreationForm):
    username = forms.CharField(
        label="使用者名稱",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    email = forms.EmailField(
        label="電子郵件",
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    password2 = forms.CharField(
        label="Password Confirmation",
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProjectSearch(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('CompanyCode', 'ProjectName')


class CompanySearch(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('CompanyCode',)


class ProjectForm(forms.ModelForm):
    CalculateStartDate = forms.DateTimeField(
        widget=forms.DateTimeInput(format='%Y-%m-%dT%H:%M',
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Select a date',
                                          'type': 'datetime-local'})
    )
    CalculateEndDate = forms.DateTimeField(
        widget=forms.DateTimeInput(format='%Y-%m-%dT%H:%M',
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Select a date',
                                          'type': 'datetime-local'})
    )

    class Meta:
        model = Project
        fields = ('CompanyCode', 'ProjectCode', 'ProjectName', 'CalculateStartDate', 'CalculateEndDate', 'IgnoreSecond')


class TestMemberForm(forms.ModelForm):
    class Meta:
        model = TestMemberList
        fields = ('ProjectCode', 'UnitName', 'MemberNumber', 'Email')


class ProjectMailForm(forms.ModelForm):
    class Meta:
        model = MailList
        fields = (
           'Title', 'Sender', 'Sender_Mail')


class UploadForm(forms.Form):
    upload = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control', 'accept': 'text/csv'})
    )


class HTMLUploadForm(forms.Form):
    upload = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control', 'accept': 'text/html'})
    )


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('CompanyCode', 'CompanyName')

SE_server/templates/project/All_Scroe.html
            <h4 class="mb-4">第二階段分數</h4>

            <div class="row mx-auto">
                <div class="card">
                    <div class="card-body">

                            <div class="row mx-auto table-responsive">
                                <table class="table table-striped col-auto" id="table1" style="text-align:center;overflow-x: auto;
                                                                            white-space: nowrap;">
                                    <thead>
                                    <tr>
                                        <th scope="col">組別</th>
                                        <th scope="col">信件一得分</th>
                                        <th scope="col">信件二得分</th>
                                        <th scope="col">信件三得分</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for score in all_group_score %}
                                        <tr>
                                            <td>{{ score.group_name }}</td>
                                            {% if score.mail1 == None %}
                                                <td>-</td>
                                            {% else %}
                                                <td>{{ score.mail1 }}</td>
                                            {% endif %}
                                            {% if score.mail2 == None %}
                                                <td>-</td>
                                            {% else %}
                                                <td>{{ score.mail2 }}</td>
                                            {% endif %}
                                            {% if score.mail3 == None %}
                                                <td>-</td>
                                            {% else %}
                                                <td>{{ score.mail3 }}</td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                    </div>
                </div>
            </div>

SE_server/templates/project/Project.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load Template_Filter %}
{% load guardian_tags %}

{% block search %}
    <form action="" method="POST" class="mb-0">
        {% csrf_token %}
        <div class="row mx-auto ">
            <div class="mb-0 col-auto">
                <select name="CompanyCode" class="form-control" id="CompanyCode">
                    <option value="default" selected>搜尋公司名稱</option>
                    {% for company in CompanyList %}
                        {% if company.CompanyCode != 'AA' %}
                            {% get_obj_perms request.user for company as "company_perms" %}
                            {% if 'view_company' in company_perms %}
                                <option value="{{ company.CompanyCode }}">
                                    {{ company.CompanyName }}</option>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="mb-0 col-auto">
                <input type="text" name="ProjectName" id="ProjectName" class="form-control" placeholder="搜尋專案名稱">
            </div>
            <div class="mb-0 col-auto">
                <input class="btn btn-outline-primary col-auto" type="submit" value="搜尋">
            </div>
        </div>
    </form>
{% endblock %}

{% block content %}
    <div class="page-content">
        <section class="row mx-auto">
            <h1 class="mb-4">課程列表</h1>
            {% comment %}
            <div class="row mx-auto">
                <div class="card">
                    <div class="card-body">
                        <h4>搜尋列</h4>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="row align-items-end mx-auto">
                                <div class="mb-3 col-3">
                                    <label class="form-label">公司名稱</label>
                                    <select name="CompanyCode" class="form-control" id="CompanyCode">
                                        <option value="default" selected>搜尋全部</option>
                                        {% for company in CompanyList %}
                                            {% if company.CompanyCode != 'AA' %}
                                                {% get_obj_perms request.user for company as "company_perms" %}
                                                {% if 'view_company' in company_perms %}
                                                    <option value="{{ company.CompanyCode }}">
                                                        {{ company.CompanyName }}</option>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="mb-3 col-3">
                                    <label class="form-label">專案名稱</label>
                                    <input type="text" name="ProjectName" id="ProjectName" class="form-control">
                                </div>
                                <div class="mb-3 col-3">
                                    <input class="btn btn-outline-primary col-auto" type="submit" value="搜尋">
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
            {% endcomment %}
            {% if SearchValue %}
                <div class="row mx-auto">
                    <div class="col-1">
                        <p>已搜尋</p>
                    </div>
                    <div class="col-auto">
                        <p>公司名稱:
                            {% for company in Company %}
                                {% if company.CompanyCode != 'AA' %}
                                    {% get_obj_perms request.user for company as "company_perms" %}
                                    {% if 'view_company' in company_perms %}
                                        {{ company.CompanyName }},
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                        </p>
                    </div>
                    <div class="col-auto">
                        <p>專案名稱:{{ ProjectName }}</p>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'project' %}">返回列表</a>
                    </div>
                </div>
            {% endif %}
            {% for company in Company %}
                {% if company.CompanyCode != 'AA' %}
                    {% get_obj_perms request.user for company as "company_perms" %}
                    {% if 'view_company' in company_perms %}
                        <div class="row mx-auto">
{#                            {% if 'AA' in user.groups.all.0.Company.all.0.CompanyCode %}#}
                                <div class="row col-auto col-md-auto">
                                    <div class="card">
                                        <div class="card-body CompanyName">
                                            <h4>課程名稱<br></h4>
                                            <h5>{{ company.CompanyName }}</h5>
                                        </div>
                                    </div>
                                </div>
                                <div class="row col col-md-1">

                                </div>
{#                            {% endif %}#}
                        </div>
                        <div class="row mx-auto">
                            <div class="card">
                                <div class="card-body table-responsive col-auto">
                                    {% get_obj_perms request.user for company as "company_perms" %}
{#                                    {% if 'exe_company' in company_perms %}#}
{#                                        <div class="row mx-auto">#}
{#                                            <div class="col-1">#}
{#                                                <button type="button" class="btn btn-primary"#}
{#                                                        hx-get="{% url 'add_project' pk=company.pk %}"#}
{#                                                        hx-target="#dialog">#}
{#                                                    新增#}
{#                                                </button>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    {% endif %}#}
                                    <br>
                                    {% if company.ProjectCount != 0 %}
                                        <div class="row mx-auto">
                                            <table class="table table-striped" id="table1" style="text-align:center;overflow-x: auto;
                                                                            white-space: nowrap;">
                                                <thead>
                                                <tr>
                                                    <th>編號</th>
                                                    <th>執行階段</th>
                                                    <th>課程開始日期</th>
                                                    <th>課程結束日期</th>
                                                    <th>查看</th>
{#                                                    {% if perms.socialapp.delete_project %}#}
{#                                                        <th>刪除</th>#}
{#                                                    {% endif %}#}
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for project in company.Company.all|dictsort:"ProjectCode" %}
                                                    {% if ProjectName in project.ProjectName or ProjectName is None %}
                                                        {% get_obj_perms request.user for project as 'project_perms' %}
                                                        {% if 'view_project' in project_perms %}
                                                            <tr>
                                                                <td>{{ forloop.counter }}</td>
                                                                <td>{{ project.ProjectName }}</td>
                                                                <td>{{ project.CalculateStartDate |date:"Y/m/d H:i:s" }}</td>
                                                                <td>{{ project.CalculateEndDate |date:"Y/m/d H:i:s" }}</td>
                                                                                                                                <td>
                                                                    <a href="project/{{ project.ProjectCode }}/"
                                                                       class="btn-sm btn-primary">查看
                                                                    </a>
                                                                </td>
{#                                                                {% if perms.socialapp.delete_project %}#}
{#                                                                    <td>#}
{#                                                                        <button type="button"#}
{#                                                                                hx-get="{% url 'delete_project' pk=project.pk %}"#}
{#                                                                                hx-target="#dialog"#}
{#                                                                                class="btn-sm btn-danger">刪除#}
{#                                                                        </button>#}
{#                                                                    </td>#}
{#                                                                {% endif %}#}
                                                            </tr>
                                                        {% endif %}
                                                    {% endif %}
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    {% else %}
                                        <div class="row mx-auto">
                                            <h4>待新增</h4>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <hr class="bg-danger border-2 border-top border-danger">
                    {% endif %}
                {% endif %}
            {% endfor %}
            {% if NULL %}
                <div class="row mx-auto">
                    <div class="card">
                        <div class="card-body">
                            <h4>尚無課程</h4>
                        </div>
                    </div>
                </div>
            {% endif %}
        </section>
    </div>
{% endblock %}

SE_server/templates/project/Project_Create_Forms.html
{% load widget_tweaks %}

{% with WIDGET_ERROR_CLASS='is-valid' %}
    <form method="POST" action="{{ request.path }}" class="modal-content" novalidate>
        {% csrf_token %}

        <div class="modal-header">
            <h1>創建執行階段</h1>
        </div>
        <div class="modal-body">
            <div class="mb-3">
                <label for="{{ form.CompanyCode.is_for_label }}" class="form-label">課程名稱</label>
                <select name="CompanyCode" class="form-control" id="id_CompanyCode" readonly="readonly">
                    <option value="{{ Company.CompanyCode }}" readonly="readonly" selected>{{ Company.CompanyName }}</option>
                </select>
                <div class="invalid-feedback">{{ form.CompanyCode.errors|first }}</div>
            </div>
            <div class="mb-3">
                <label for="{{ form.ProjectName.is_for_label }}" class="form-label">執行階段名稱</label>
                {% render_field form.ProjectName class="form-control" %}
                <div class="invalid-feedback">{{ form.ProjectName.errors|first }}</div>
            </div>
            <div class="mb-3">
                <label for="{{ form.CalculateStartDate.is_for_label }}"
                       class="form-label">統計開始日期</label>
                {% render_field form.CalculateStartDate class="form-control"%}
                <div class="invalid-feedback">{{ form.CalculateStartDate.errors|first }}</div>
            </div>
            <div class="mb-3">
                <label for="{{ form.CalculateEndDate.is_for_label }}" class="form-label">統計結束日期</label>
                {% render_field form.CalculateEndDate class="form-control" placeholder="2000/01/01 00:00:00" %}
                <div class="invalid-feedback">{{ form.CalculateEndDate.errors|first }}</div>
            </div>
            <div class="mb-3">
                <label for="{{ form.IgnoreSecond.is_for_label }}" class="form-label">統計週期</label>
                {% render_field form.IgnoreSecond class="form-control" placeholder="60(單位:秒)" %}
                <div class="invalid-feedback">{{ form.IgnoreSecond.errors|first }}</div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
            <button type="submit" class="btn btn-primary">儲存</button>
        </div>
    </form>
{% endwith %}

SE_server/templates/project/Project_Mail_Delete.html
{% load widget_tweaks %}

{% with WIDGET_ERROR_CLASS='is-valid' %}
    <form method="POST" action="{{ request.path }}" class="modal-content">
        {% csrf_token %}
        <div class="modal-header">
            <h1>刪除</h1>
        </div>
        <div class="modal-body">
            <p>確定刪除{{ Mail.MailNumber }}嗎</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
            <button type="submit" class="btn btn-primary">確定</button>
        </div>
    </form>
{% endwith %}

SE_server/templates/project/Report_Back.html
{% extends 'base.html' %}
{% load Template_Filter %}
{% load guardian_tags %}

{% block content %}
    <form method="POST" action="{{ request.path }}" class="modal-content" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="modal-header">
            <h1>回覆可疑信件</h1>
        </div>
        <div class="modal-body">
{#            <div class="mb-3">#}
{#                <label class="form-label">請輸入組別編號</label>#}
{#                <input type="text" class="form-control" name="group" required="required">#}
{#            </div>#}
            <div class="mb-3">
                <label class="form-label">請輸入信件標題</label>
                <input type="text" class="form-control" name="title" required="required">
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">送出</button>
        </div>
    </form>

{% endblock %}